# Generated by Django 5.2 on 2025-05-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoatStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Boat",
                        max_length=50,
                        unique=True,
                        verbose_name="name of the boat",
                    ),
                ),
                ("lat", models.FloatField(default=0.0, verbose_name="latitude")),
                ("lon", models.FloatField(default=0.0, verbose_name="longitude")),
                (
                    "mode",
                    models.TextField(
                        default="idle", max_length=35, verbose_name="mode"
                    ),
                ),
                ("speed", models.IntegerField(default=0, verbose_name="speed")),
                ("heading", models.IntegerField(default=0, verbose_name="direction")),
                ("battery", models.IntegerField(default=0, verbose_name="battery")),
                (
                    "source",
                    models.TextField(
                        default="system", max_length=50, verbose_name="source"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="Default Settings", verbose_name="message"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="timestamp"),
                ),
                ("status", models.BooleanField(default=None, verbose_name="status")),
            ],
            options={
                "verbose_name": "BoatStatus",
                "verbose_name_plural": "BoatStatus",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(default="default.jpg", upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
