# Generated by Django 5.2 on 2025-06-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boatstatus",
            options={},
        ),
        migrations.RemoveField(
            model_name="boatstatus",
            name="name",
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="heading",
            field=models.FloatField(default=0.0, verbose_name="heading"),
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="mode",
            field=models.CharField(default="idle", max_length=35, verbose_name="mode"),
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="source",
            field=models.CharField(
                default="system", max_length=50, verbose_name="source"
            ),
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="speed",
            field=models.FloatField(default=0.0, verbose_name="speed"),
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="status",
            field=models.BooleanField(default=False, verbose_name="status"),
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "controller_status",
                    models.CharField(default="MANUAL", max_length=50),
                ),
                ("is_emergency_stop", models.BooleanField(default=False)),
                ("motor_left_speed", models.FloatField(default=0.0)),
                ("motor_right_speed", models.FloatField(default=0.0)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_status",
                        to="api.vessel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("gps_lat", models.FloatField()),
                ("gps_lng", models.FloatField()),
                ("speed", models.FloatField()),
                ("heading", models.FloatField()),
                ("imu_pitch", models.FloatField(blank=True, null=True)),
                ("imu_roll", models.FloatField(blank=True, null=True)),
                ("imu_yaw", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("battery_voltage", models.FloatField(blank=True, null=True)),
                ("battery_current", models.FloatField(blank=True, null=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="api.vessel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PathLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("path_points", models.JSONField()),
                ("method_used", models.CharField(default="manual", max_length=50)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_logs",
                        to="api.vessel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("error_code", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_logs",
                        to="api.vessel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="boatstatus",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="api.vessel",
            ),
        ),
        migrations.CreateModel(
            name="VideoStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("image_path", models.CharField(blank=True, max_length=255)),
                ("detected_objects", models.JSONField(blank=True, null=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_streams",
                        to="api.vessel",
                    ),
                ),
            ],
        ),
    ]
