# Generated by Django 5.2 on 2025-06-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_boatstatus_options_remove_boatstatus_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boatstatus",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="api.vessel",
            ),
        ),
    ]
