# Generated by Django 5.2 on 2025-06-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_boatstatus_vessel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boatstatus",
            name="vessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="api.vessel",
            ),
        ),
    ]
