# Generated by Django 5.2 on 2025-06-14 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_boatstatus_vessel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="boatstatus",
            name="mode",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("manual", "Manual"),
                    ("auto", "Autonomous"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boatstatus",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.vessel"
            ),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
