# Generated by Django 5.2 on 2025-06-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_boatstatus_mode_alter_boatstatus_vessel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boatstatus",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "BoatStatus",
                "verbose_name_plural": "BoatStatus",
            },
        ),
    ]
